language: ruby
rvm:
 - 2.5.1
services:
  - postgresql
script:
  - RAILS_ENV=test bundle exec rake db:setup
  - RAILS_ENV=test bundle exec rake
before_script:
  - psql -c 'create database demand_progress_test' -U demand-progress
